#pragma once

#define SERVER_NAME_LEN_MAX 255
#define MAX_MESSAGE_SIZE 1024  // bytes
#define MAX_CONNECT_RETRIES 3
#define PROTOCOL_LEN 3

#define MSG_HEADER_SIZE 12  // 2 is size of type, 4 is len of MAX_MESSAGE_SIZE

#define PROTOCOL_V_STRINGIFY_HELPER(x, y) #x "." #y
#define PROTOCOL_V_STRINGIFY(x, y) PROTOCOL_V_STRINGIFY_HELPER(x, y)
#define PROTOCOL_V PROTOCOL_V_STRINGIFY(PROTOCOL_MAJORV, PROTOCOL_MINORV)

enum PACKET_TYPES { HELLO, WELCOME, REJECT, GOODBYE, PING, PONG };
